# scan_batch_config.yaml
# Archivo de configuración para escaneo masivo de directorios
# Archivo de configuración para escaneo masivo de directorios
projects:
  - path: C:\DevOps\MyGitHub\Udemy\amazonashop\QA\tests\performance
    ignore_file: scan_ignore_python.yaml
    output: salida_performance_k6.txt

  - path: C:\DevOps\MyGitHub\Udemy\amazonashop\Backend
    ignore_file: scan_ignore_dotnet.yaml
    output: salida_backend.txt
